/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "and_gate.v:1.1-6.10" *)
module and_gate(a, b, y);
  (* src = "and_gate.v:2.7-2.8" *)
  input a;
  wire a;
  (* src = "and_gate.v:2.9-2.10" *)
  input b;
  wire b;
  (* src = "and_gate.v:3.8-3.9" *)
  output y;
  wire y;
  AND2X1 _0_ (
    .A(a),
    .B(b),
    .Y(y)
  );
endmodule
